### ISSUE TITLE
Add Cells API status info to status.json

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/gateway#133]
Add the status of the Cells API to the main status.json, available here: https://cells.api.hubmapconsortium.org/api/status/

reference: https://github.com/hubmapconsortium/portal-ui/issues/2210

**Comment by yuanzhou** [comment]
@shirey @DerekFurstPitt The cells api status has been added to Gateway and released to PROD. Matt or Sean is making a small tweak to use `postgres_connection` as the key in the json instead of `Postgres connection` which contains a white space and causing parsing issue that requires a special handling. They've updated on DEV, we are waiting for the corresponding fix on TEST and PROD then make a quick fix in gateway too.
