### ISSUE TITLE
hubmap-docker.sh should include ingest-pipeline in fully dockerized environment

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/gateway#15]
hubmap-docker.sh both builds docker containers and launches the network of containers. It might as well treat ingest-pipeline like all the other components; this is done in welling_ingest_pipeline_tweaks_201912 but has not been merged back to master.  There is some lack of clarity about what should happen for various combinations of [dev,test,prod] x [check,build,start,stop].  Should 'start' ever get used in test or prod mode? Which host is it intended to be run from, and can it check that it is running in the right place?  Does dev really mean 'local-dev'?

**Comment by yuanzhou** [comment]
Here are the answers:

- `dev` currently really means 'local-dev', which builds all the images and starts all the containers on localhost on different ports.
- `test` and `prod` are different form `dev` in that it involves two host machines rather than one. On testing deployment, ingest-api is deployed on one machine that has access to the mounted Globus endpoints. I think ingest-pipeline will be on the same machine as well. All other APIs (uuid-api, entity-api, and ingest-ui) are deployed on another machine. 
- `test` should be as close as `prod` in terms of deployment environment and infrastructure. One obvious difference will be each API will has a different sub-domain name. E.g., ingest-api.test.hubmapconsortium.or VS ingest.api.hubmapconsortium.org. They also run on HTTPS instead of HTTP, which requires SSL certificates on each machine. So the nginx config will be slightly different.
- the usage of `build`, `start`, and `stop` commands are the same for each deployment mode.
- I think we should include your work on ingest-pipeline into this stack for all `dev`, `test`, and `prod` so we'll have the whole workflow. The unclear part is how can we configure the Globus mounting for local dev?
- for `prod` mode, since we'll be deploying ingest-api and ingest-pipeline on the PSC machine, we'll need to figure out some SSL stuff as well as Globus related things.

**Comment by jswelling** [comment]
I propose that for local dev the ingest-pipeline .cfg file be modified to run the MOCK. versions of pipelines rather than the actual (non-MOCK) versions.  Those generate appropriate replies from pre-recorded data (see the data/mock subdirectory of ingest-pipeline).  That would let test users model the whole component interaction without actual Globus access.  (landing-zone creation is separate, but that issue doesn't actually involve ingest-pipeline).

**Comment by yuanzhou** [comment]
Some questions we'll need to think about:

- Is ingest-pipeline only used by ingest-api? We don't have to put it behind gateway if ingest-pipeline is not supposed to be exposed to outside or it doesn't require authentication at all.

- in the `dev` mode, ingest-pipeline is running with Flask development server, we'll probably need to run with nginx for testing and production. That requires different configurations other than using environment variables maybe.

**Comment by yuanzhou** [comment]
Pulling @shirey into this discussion.

**Comment by shirey** [comment]
Let's get the MOCK version in for local dev.   We need to think about how we handle for our AWS TEST instance.  I'd say discuss after the break.

**Comment by jswelling** [comment]
Re @yuanzhou 's questions: 

- At the moment, ingest-pipeline is only used by ingest-api.  We presumably want to use other special-purpose Airflow workflows, though- like for random heavy lifting required by downstream tools.  That suggests that ingest-pipeline should be behind the gateway.  There is some benefit to having Airflow's native UI visible, and we have a work item to protect it via our Globus tokens.

- ingest-pipeline is actually a plug-in to Airflow's native UI, which I believe always runs under Flask/gunicorn. At least for prod that plan is to run an nginx server on the same host in front of that UI. That server has been configured by PSC but maybe we should pull its config into what is managed by gateway?  Pulling in @pdblood for that one.

**Comment by shirey** [comment]
@yuanzhou ingest-pipeline is an API/ws which we can MAYBE put behind the gateway.  @jswelling If ingest-pipeline is on the same base URL as other web services that airflow needs we may not be able to put your calls behind the gateway without putting those behind the gateway as well, and they won't have the Globus token that we need.

**Comment by yuanzhou** [comment]
Thanks @shirey and @jswelling, let's start merging pipeline docker related things into the gateway script for local dev first.

**Comment by yuanzhou** [comment]
No longer relevant
